### ISSUE TITLE
requirements.txt not included

### ISSUE THREAD

**Issue by inktrap** [dgrant/django_recipes#7]
The two create-env scripts need it, but requirements.txt is not included in the project.

**Comment by dgrant** [comment]
Ah, sorry I'm using pipenv now. I'll remove anything that still depends on requirements.txt

**Comment by rootjalex** [comment]
./createVirtualEnv.sh still depends on requirements.txt and it is not included. What is the workaround, or can you provide the file?

**Comment by dgrant** [comment]
I've removed the requirements.txt file and updatd the instructions. Let me know if you still need more help.
